from enum import Enum


class TileType(Enum):
    EMPTY = 0
    START_EAST = 1
    START_WEST = 2
    START_NORTH = 3
    START_SOUTH = 4
    EAST_END = 5
    WEST_END = 6
    NORTH_END = 7
    SOUTH_END = 8
    FLOW_RATE_CALCULATOR_HORIZONTAL = 9
    FLOW_RATE_CALCULATOR_VERTICAL = 10
    STRAIGHT_HORIZONTAL = 11
    STRAIGHT_VERTICAL = 12
    TURN_WEST_NORTH = 13
    TURN_WEST_SOUTH = 14
    TURN_EAST_NORTH = 15
    TURN_EAST_SOUTH = 16
    DIVISION_2_FROM_EAST = 17
    DIVISION_2_FROM_WEST = 18
    DIVISION_2_FROM_NORTH = 19
    DIVISION_2_FROM_SOUTH = 20
    DIVISION_3 = 21
