# Connect the stl files generated by the two scripts to create a 3D maze.
import numpy as np
import trimesh
from build_3D import build_3d_maze, create_box_between_points, create_cylinder_between_points


def main():
    import numpy as np
    import trimesh
    from build_3D import build_3d_maze

    # Import the stl maze from the folder
    maze1 = trimesh.load_mesh('maze_east.stl')
    maze2 = trimesh.load_mesh('maze_north.stl')
    maze3 = trimesh.load_mesh('maze_north.stl')
    base = trimesh.load_mesh('base.stl')

    # Turn the maze3 90 degrees
    maze3.apply_transform(trimesh.transformations.rotation_matrix(np.pi/2, [0, 0, 1]))

    # Add the two mazes after each other
    maze2.apply_translation([10, 0, 0])
    maze3.apply_translation([20, 10, 0])
    maze = trimesh.util.concatenate([maze1, maze2, maze3])

    # Save the mesh to file
    maze.show()


if __name__ == '__main__':
    main()
